# Generated by Django 4.2.13 on 2024-07-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedprediction",
            name="project_name",
            field=models.CharField(default="Unknown Project", max_length=100),
        ),
    ]
